name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to VPS
        run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete . root@82.115.17.24:/home/DMS/Dehyar-Management-Service-FrontEnd

      - name: Run Docker Compose
        run: ssh -o StrictHostKeyChecking=no root@82.115.17.24 "cd /home/DMS/Dehyar-Management-Service-FrontEnd && docker-compose up -d --build"
